@version=v1

### INDEX
GET http://{{host}}/{{version}}/employees?page=1&page_size=10&filter=[]&sort=[] HTTP/1.1
Authorization: Bearer {{token}}


### DETAIL
GET http://{{host}}/{{version}}/employees/ HTTP/1.1
Authorization: Bearer {{token}}


### CREATE
POST http://{{host}}/{{version}}/employees HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name" : "John Doe",
  "position" : "Software Engineer",
  "department" : "IT",
  "supervisor" : "Jane Doe"
}


### UPDATE
PUT http://{{host}}/{{version}}/employees HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "id" : "e21a475b-f7a6-4305-81e9-efbe9d9c13f5",
  "employee_code" : "EMP-9XFD",
  "name" : "John Doe Edited",
  "position" : "Marketing Manager",
  "department" : "Marketing",
  "supervisor" : "Jane Doe"
}


### DELETE
DELETE  http://{{host}}/{{version}}/employees HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "id" : ""
}